Added find_mac and find_ip action and aliases
StackStorm-Exchange/stackstorm-cisco_aci pull request #14
Opened 2020-02-05 21:08 UTC by jcoeder

Added find_mac and find_ip action and aliases

2020-02-07 01:44 UTC, nmaludy requested changes
Couple small changes. There are some examples of unit tests in the tests directory.

2020-02-07 01:44 UTC, nmaludy commented on actions/find_ip.py
> +class findIP(ACIBaseActions):
Class names should start with a Capital Letter

2020-02-07 01:44 UTC, nmaludy commented on actions/find_ip.py
> +    def run(self, apic="default", credentials=None, ip=None):
the apic field is marked as `required: true` in the action metadata, yet you set it to a default string here in the python, need to pick one. Either set a default in the action metadata or remove the default in the python file. Similarly, if `ip` is marked required in the action metadata, you should remove the default here in the python file.

2020-02-07 01:44 UTC, nmaludy commented on README.md
> +* `cisco_aci.find_mac` - Find a MAC address in the fabric
Missing a changelog entry in CHANGES.md

2020-02-07 01:44 UTC, nmaludy commented on actions/find_ip.py
> +# Licensed to the StackStorm, Inc ('StackStorm') under one or more
Missing unit tests for new python code.

2020-02-07 15:08 UTC, armab commented on pack.yaml
> +version: 0.1.7
```suggestion
version: 0.2.0
```

Considering this PR is not a bugfix, but a feature with new changes, please bump the version accordingly to https://semver.org/#summary

2020-02-09 19:58 UTC, jcoeder commented
Made recommended changes.  Tests are very basic - based on existing tests.

2020-02-09 20:22 UTC, nmaludy requested changes
Getting better! Just need some actual tests and you'll be good!

2020-02-09 20:22 UTC, nmaludy commented on tests/test_action_find_ip.py
> +class GetAPsActionTestCase(CiscoACIBaseActionTestCase):
This is good boiler plate, but now you need some actual test functions that perform tests on your code.

2020-02-09 20:24 UTC, nmaludy commented
I see why you're confused on the tests, because the ones in this pack are bad examples and don't actually test anything. Let me try to find an example from another pack.

2020-02-09 20:28 UTC, nmaludy commented
@jcoeder here is a good example https://github.com/StackStorm-Exchange/stackstorm-vsphere/blob/master/tests/test_action_get_tags_on_object.py#L30

There are a couple other good ones in that pack.

The general idea is: 
- Create an instance of your action
- Mock out any functions that will make a connection over a network. You setup these mocks to return fake data instead of going over network.
- Run your function with some test data
- Compare the results you get back with what you think you should expect knowing what the function is supposed to do.

2020-04-30 12:28 UTC, nmaludy approved these changes
LGTM!

2020-04-30 12:29 UTC, merged